
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 24 14:34:22 EET 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface CUP_FILESym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int LTE = 25;
  public static final int STR = 34;
  public static final int INTEGER = 22;
  public static final int LPAREN = 8;
  public static final int INT = 32;
  public static final int MINUS = 5;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 14;
  public static final int LT = 24;
  public static final int COMMA = 17;
  public static final int CLASS = 16;
  public static final int PLUS = 4;
  public static final int ASSIGN = 15;
  public static final int IF = 2;
  public static final int DOT = 3;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 18;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int NULL = 27;
  public static final int VOID = 30;
  public static final int GTE = 21;
  public static final int LBRACK = 10;
  public static final int TIMES = 6;
  public static final int LBRACE = 12;
  public static final int RBRACK = 11;
  public static final int WHILE = 31;
  public static final int NEQUAL = 26;
  public static final int CLASS_ID = 35;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 19;
  public static final int STRING = 29;
  public static final int GT = 20;
}

